# Generated by Django 4.1 on 2023-02-23 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("course_id", models.AutoField(primary_key=True, serialize=False)),
                ("course_number", models.CharField(max_length=20)),
                ("course_name", models.CharField(max_length=255)),
            ],
            options={"ordering": ["course_number", "course_name"],},
        ),
        migrations.CreateModel(
            name="Instructor",
            fields=[
                ("instructor_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=45)),
                ("last_name", models.CharField(max_length=45)),
                (
                    "disambiguator",
                    models.CharField(blank=True, default="", max_length=45),
                ),
            ],
            options={"ordering": ["last_name", "first_name", "disambiguator"],},
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                ("period_id", models.AutoField(primary_key=True, serialize=False)),
                ("period_sequence", models.IntegerField(unique=True)),
                ("period_name", models.CharField(max_length=45, unique=True)),
            ],
            options={"ordering": ["period_sequence"],},
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "registration_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
            ],
            options={"ordering": ["section", "student"],},
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                ("section_id", models.AutoField(primary_key=True, serialize=False)),
                ("section_name", models.CharField(max_length=20)),
            ],
            options={"ordering": ["course", "section_name", "semester"],},
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                ("semester_id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={"ordering": ["year__year", "period__period_sequence"],},
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("student_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=45)),
                ("last_name", models.CharField(max_length=45)),
                (
                    "disambiguator",
                    models.CharField(blank=True, default="", max_length=45),
                ),
            ],
            options={"ordering": ["last_name", "first_name", "disambiguator"],},
        ),
        migrations.CreateModel(
            name="Year",
            fields=[
                ("year_id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField(unique=True)),
            ],
            options={"ordering": ["year"],},
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                fields=("last_name", "first_name", "disambiguator"),
                name="unique_student",
            ),
        ),
        migrations.AddField(
            model_name="semester",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="semesters",
                to="courseinfo.period",
            ),
        ),
        migrations.AddField(
            model_name="semester",
            name="year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="semesters",
                to="courseinfo.year",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sections",
                to="courseinfo.course",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sections",
                to="courseinfo.instructor",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sections",
                to="courseinfo.semester",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registrations",
                to="courseinfo.section",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registrations",
                to="courseinfo.student",
            ),
        ),
        migrations.AddConstraint(
            model_name="instructor",
            constraint=models.UniqueConstraint(
                fields=("last_name", "first_name", "disambiguator"),
                name="unique_instructor",
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                fields=("course_number", "course_name"), name="unique_course"
            ),
        ),
        migrations.AddConstraint(
            model_name="semester",
            constraint=models.UniqueConstraint(
                fields=("year", "period"), name="unique_semester"
            ),
        ),
        migrations.AddConstraint(
            model_name="section",
            constraint=models.UniqueConstraint(
                fields=("semester", "course", "section_name"), name="unique_section"
            ),
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.UniqueConstraint(
                fields=("section", "student"), name="unique_registration"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="registration", unique_together={("section", "student")},
        ),
    ]
