# Generated by Django 4.1 on 2023-04-27 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courseinfo", "0005_create_group_permissions"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="registration", unique_together=set(),),
    ]
